env:
  JDK_VERSION: '17'
  SPIGOT_VERSION: 1.18.1
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ env.JDK_VERSION }}
    - continue-on-error: true
      name: Compile Spigot with BuildTools
      uses: SpraxDev/Action-SpigotMC@v3
      with:
        buildToolProvider: SpigotMC
        versions: ${{ env.SPIGOT_VERSION }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      id: prep
      name: Resolve .jar name
      run: 'JAR_PATH=`echo target/Mammoth*.jar`

        JAR_NAME=`basename ${JAR_PATH}`


        echo ::set-output name=jar_path::${JAR_PATH}

        echo ::set-output name=jar_name::${JAR_NAME}

        '
    - continue-on-error: true
      if: contains(github.ref, 'refs/tags/') == false
      name: Upload .jar
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prep.outputs.jar_name }}
        path: ${{ steps.prep.outputs.jar_path }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      if: contains(github.ref, 'refs/tags/') == true
      name: Create Release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: Mammoth ${{ github.ref }}
        tag_name: ${{ github.ref }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: contains(github.ref, 'refs/tags/') == true
      name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/java-archive
        asset_name: ${{ steps.prep.outputs.jar_name }}
        asset_path: ${{ steps.prep.outputs.jar_path }}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
name: Java Build
on:
  repository_dispatch:
    types: trigger-ga___java.yml
